### ISSUE TITLE
Can't use healing items when health is at/above 20.

### ISSUE THREAD

**Issue by DeadSeaHacks** [xsmeths/MedCraft#1]
The Bandages and MedKit can't be used when your health is at the vanilla maximum or higher, this means with custom datapacks, plugins or commands that give you extra health you can not heal that using these items unless you drop below 20 health (10 hearts).

**Comment by xsmeths** [comment]
huh, I think this may have been fixed, will release 1.3.4 soon, it has many improvements but can you provide the server version and plugin version you are using for me?

**Comment by xsmeths** [comment]
releases 1.3,4, please try it out and let me know if it works, it is on both spigot and the releases tab over here on GitHub
