### ISSUE TITLE
Cant craft Paper -- permission Error

### ISSUE THREAD

**Issue by JaHollTV** [xsmeths/MedCraft#2]
Using MCPaper 1.14.4: When a Player tries to craft normal Paper the Plugin says he needs the permission medkit.craft

**Comment by xsmeths** [comment]
okay, this is already fixed in the code, but will release a patch update later on today, thank you for your report

**Comment by xsmeths** [comment]
just released 1.3.5.1 which fixes your issue, please reopen the issue if it is not fixed but it should be, also added some new configuration you may get some use out of
