### ISSUE TITLE
SPAM with plugin trying calculate

### ISSUE THREAD

**Issue by wryel2000** [xsmeths/MedCraft#6]
hello dude, i love u plugin but have a little problem about this:

[08:45:15 WARN]: [MedCraft] Task #-1776937214 for MedCraft v2.0.3.2 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and rust
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.5.jar:git-Purpur-1171]
        at me.smeths.and.rhetorical.Handlers.MedicalHandler$1.run(MedicalHandler.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        
        
        in this world and others more, i have this error, i dont know if player using bandagem before teleport btw.
        
        
        this is my config file
        
        PAPER:
  '2':
    DropIfNotUsed: true
    HasRange: false
    Radius: 1.13
    Warmup-Speed: 5
    Result-Amount: 2
    Name: '#FF0000✚#FFFFFFBandagem#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use this Bandage'
    - '#666666-------------------------------------'
    - '#FFA500Because floris is my lord and saviour'
    Regen-Time: 6
    Regen-Amplifier: 2
    Craftable: true
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: ' 2 '
    Crafting-Shape-middle-row: '456'
    Crafting-Shape-bottom-row: ' 8 '
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: tell [playername] Algumas feridas foram estancadas...
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido!
    InternalName: BANDAGE
  '7':
    DropIfNotUsed: true
    HasRange: false
    Radius: 1.13
    Warmup-Speed: 5
    Result-Amount: 1
    Name: '#FF0000✚#FFFFFFMorphina#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use this Bandage'
    - '#666666-------------------------------------'
    Regen-Time: 1
    Regen-Amplifier: 1
    Craftable: false
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: ' 2 '
    Crafting-Shape-middle-row: '456'
    Crafting-Shape-bottom-row: ' 8 '
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: effect give [playername] minecraft:health_boost 20 1 true 
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] O uso falhou, se mantenha parado!
    InternalName: Morphina   
  '8':
    DropIfNotUsed: true
    HasRange: false
    Radius: 1.13
    Warmup-Speed: 5
    Result-Amount: 1
    Name: '#FF0000✚#FFFFFFEpinefrina#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use this Bandage'
    - '#666666-------------------------------------'
    Regen-Time: 1
    Regen-Amplifier: 1
    Craftable: false
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: ' 2 '
    Crafting-Shape-middle-row: '456'
    Crafting-Shape-bottom-row: ' 8 '
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: effect give [playername] minecraft:speed 30 1 true 
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] O uso falhou, se mantenha paradoe use apenas ferido!
    InternalName: Epinefina       
  '4':
    DropIfNotUsed: true
    HasRange: false
    Radius: 1.1
    Warmup-Speed: 1
    Result-Amount: 3
    Name: '#FF0000✚#FFFFFFAtadura#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use'
    - '#666666------------------------------'
    Regen-Time: 3
    Regen-Amplifier: 3
    Craftable: true
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: '   '
    Crafting-Shape-middle-row: 4 6
    Crafting-Shape-bottom-row: ' 8 '
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: tell [playername] Algumas feridas foram estancadas...
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido!
    InternalName: SMALLBANDAGE
  '5':
    DropIfNotUsed: true
    HasRange: true
    Radius: 6.66
    Warmup-Speed: 1
    Result-Amount: 1
    Name: '#FF0000✚#FFFFFFMedKit#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use'
    - '#666666-----------------------------'
    Regen-Time: 9
    Regen-Amplifier: 2
    Craftable: true
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: '123'
    Crafting-Shape-middle-row: '456'
    Crafting-Shape-bottom-row: '789'
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: tell [playername] Algumas feridas foram estancadas...
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido!
    InternalName: MEDKIT
  '3':
    DropIfNotUsed: true
    HasRange: true
    Radius: 3.33
    Warmup-Speed: 2
    Result-Amount: 3
    Name: '#FF0000✚#FFFFFFAntibiotico#FF0000✚'
    Lore:
    - '#FFA500Right/Left click to use'
    - '#666666-----------------------'
    Regen-Time: 4
    Regen-Amplifier: 4
    Craftable: true
    Crafting-Material-top-left: PAPER
    Crafting-Material-top-middle: PAPER
    Crafting-Material-top-right: PAPER
    Crafting-Material-middle-left: PAPER
    Crafting-Material-center: PAPER
    Crafting-Material-middle-right: PAPER
    Crafting-Material-bottom-left: PAPER
    Crafting-Material-bottom-middle: PAPER
    Crafting-Material-bottom-right: PAPER
    Crafting-Shape-top-row: '12 '
    Crafting-Shape-middle-row: 4 6
    Crafting-Shape-bottom-row: ' 89'
    PerformSuccessCMD: true
    ConsoleSuccessCMD: true
    SuccessCMD: tell [playername] Algumas feridas foram estancadas...
    PerformFailureCMD: false
    ConsoleFailureCMD: false
    FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido!
    InternalName: SMALLMEDKIT 
Messages:
  NoPermCraft: 'You cannot craft [item] #FFFFFFwithout med.craft'
  NoPermUse: 'You cannot use [item] #FFFFFFwithout med.craft.use'
  NoPermUseOffhand: 'You cannot use [item] #FFFFFFin offhand without med.craft.use.offhand'
  OffhandUse: 'You have used a [item] #FFFFFFon [recipient]'
Experimental:
  Item-Pickup_Fix: Do not enable this option if you can pickup items with it set to
    false
  AlternatePickup: false

tkx for u atttention. im using 1.16.5 paper server

**Comment by xsmeths** [comment]
> hello dude, i love u plugin but have a little problem about this:
> 
> [08:45:15 WARN]: [MedCraft] Task #-1776937214 for MedCraft v2.0.3.2 generated an exception java.lang.IllegalArgumentException: Cannot measure distance between world and rust at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.5.jar:git-Purpur-1171] at me.smeths.and.rhetorical.Handlers.MedicalHandler$1.run(MedicalHandler.java:43) ~[?:?] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.Thread.run(Thread.java:831) [?:?]
> 
> ```
>     in this world and others more, i have this error, i dont know if player using bandagem before teleport btw.
>     
>     
>     this is my config file
>     
>     PAPER:
> ```
> 
> '2': DropIfNotUsed: true HasRange: false Radius: 1.13 Warmup-Speed: 5 Result-Amount: 2 Name: '#FF0000✚#FFFFFFBandagem#FF0000✚' Lore: - '#FFA500Right/Left click to use this Bandage' - '#666666-------------------------------------' - '#FFA500Because floris is my lord and saviour' Regen-Time: 6 Regen-Amplifier: 2 Craftable: true Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: ' 2 ' Crafting-Shape-middle-row: '456' Crafting-Shape-bottom-row: ' 8 ' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: tell [playername] Algumas feridas foram estancadas... PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido! InternalName: BANDAGE '7': DropIfNotUsed: true HasRange: false Radius: 1.13 Warmup-Speed: 5 Result-Amount: 1 Name: '#FF0000✚#FFFFFFMorphina#FF0000✚' Lore: - '#FFA500Right/Left click to use this Bandage' - '#666666-------------------------------------' Regen-Time: 1 Regen-Amplifier: 1 Craftable: false Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: ' 2 ' Crafting-Shape-middle-row: '456' Crafting-Shape-bottom-row: ' 8 ' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: effect give [playername] minecraft:health_boost 20 1 true PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] O uso falhou, se mantenha parado! InternalName: Morphina '8': DropIfNotUsed: true HasRange: false Radius: 1.13 Warmup-Speed: 5 Result-Amount: 1 Name: '#FF0000✚#FFFFFFEpinefrina#FF0000✚' Lore: - '#FFA500Right/Left click to use this Bandage' - '#666666-------------------------------------' Regen-Time: 1 Regen-Amplifier: 1 Craftable: false Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: ' 2 ' Crafting-Shape-middle-row: '456' Crafting-Shape-bottom-row: ' 8 ' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: effect give [playername] minecraft:speed 30 1 true PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] O uso falhou, se mantenha paradoe use apenas ferido! InternalName: Epinefina '4': DropIfNotUsed: true HasRange: false Radius: 1.1 Warmup-Speed: 1 Result-Amount: 3 Name: '#FF0000✚#FFFFFFAtadura#FF0000✚' Lore: - '#FFA500Right/Left click to use' - '#666666------------------------------' Regen-Time: 3 Regen-Amplifier: 3 Craftable: true Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: ' ' Crafting-Shape-middle-row: 4 6 Crafting-Shape-bottom-row: ' 8 ' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: tell [playername] Algumas feridas foram estancadas... PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido! InternalName: SMALLBANDAGE '5': DropIfNotUsed: true HasRange: true Radius: 6.66 Warmup-Speed: 1 Result-Amount: 1 Name: '#FF0000✚#FFFFFFMedKit#FF0000✚' Lore: - '#FFA500Right/Left click to use' - '#666666-----------------------------' Regen-Time: 9 Regen-Amplifier: 2 Craftable: true Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: '123' Crafting-Shape-middle-row: '456' Crafting-Shape-bottom-row: '789' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: tell [playername] Algumas feridas foram estancadas... PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido! InternalName: MEDKIT '3': DropIfNotUsed: true HasRange: true Radius: 3.33 Warmup-Speed: 2 Result-Amount: 3 Name: '#FF0000✚#FFFFFFAntibiotico#FF0000✚' Lore: - '#FFA500Right/Left click to use' - '#666666-----------------------' Regen-Time: 4 Regen-Amplifier: 4 Craftable: true Crafting-Material-top-left: PAPER Crafting-Material-top-middle: PAPER Crafting-Material-top-right: PAPER Crafting-Material-middle-left: PAPER Crafting-Material-center: PAPER Crafting-Material-middle-right: PAPER Crafting-Material-bottom-left: PAPER Crafting-Material-bottom-middle: PAPER Crafting-Material-bottom-right: PAPER Crafting-Shape-top-row: '12 ' Crafting-Shape-middle-row: 4 6 Crafting-Shape-bottom-row: ' 89' PerformSuccessCMD: true ConsoleSuccessCMD: true SuccessCMD: tell [playername] Algumas feridas foram estancadas... PerformFailureCMD: false ConsoleFailureCMD: false FailureCMD: tell [playername] A cura falhou, se mantenha parado e use apenas ferido! InternalName: SMALLMEDKIT Messages: NoPermCraft: 'You cannot craft [item] #FFFFFFwithout med.craft' NoPermUse: 'You cannot use [item] #FFFFFFwithout med.craft.use' NoPermUseOffhand: 'You cannot use [item] #FFFFFFin offhand without med.craft.use.offhand' OffhandUse: 'You have used a [item] #FFFFFFon [recipient]' Experimental: Item-Pickup_Fix: Do not enable this option if you can pickup items with it set to false AlternatePickup: false
> 
> tkx for u atttention. im using 1.16.5 paper server

thanks for your report, I'll look into getting this fixed up for you soon, I think I simply require a little code to cancel bandage usage when they change world during bandaging by the looks of the error, shouldn't be too much of a pain to patch, a little busy at the moment but will have this fixed for the next release on spigot :)
